"""add guardrail columns

Revision ID: 351153c8797a
Revises: f6a7b8c9d0e1
Create Date: 2026-04-11 09:24:53.141456
"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '351153c8797a'
down_revision: Union[str, None] = 'f6a7b8c9d0e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pii_mapping', sa.JSON(), nullable=True))

    with op.batch_alter_table('llm_interactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('guardrail_findings', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('llm_interactions', schema=None) as batch_op:
        batch_op.drop_column('guardrail_findings')

    with op.batch_alter_table('agent_runs', schema=None) as batch_op:
        batch_op.drop_column('pii_mapping')

    # ### end Alembic commands ###
